base: &base
    working_directory: ~/state-stack
    docker:
        - image: circleci/node:8-browsers
version: 2
jobs:
    build:
        <<: *base
        steps:
            - checkout
            - restore_cache:
                key: npm-{{ checksum "package-lock.json" }}
            - run:
                name: npm install
                command: npm install
            - save_cache:
                key: npm-{{ checksum "package-lock.json" }}
                paths: node_modules
            - run:
                name: npm run build
                command: npm run build
            - persist_to_workspace:
                root: ~/state-stack
                paths: 
                    - .
    test:
        <<: *base
        steps:
            - attach_workspace:
                at: ~/state-stack
            - run:
                name: npm test
                command: npm test
    coverage:
        <<: *base
        steps:
            - attach_workspace:
                at: ~/state-stack
            - run:
                name: npm run coverage
                command: npm run coverage
    docs:
        <<: *base
        steps:
            - attach_workspace:
                at: ~/state-stack
            - run:
                name: npm run doc
                command: npm run doc
            - store_artifacts:
                path: _book
                destination: _book
    deploy:
        <<: *base
        steps:
            - attach_workspace:
                at: ~/state-stack
            - run:
                name: npm publish
                command: |
                    echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
                    npm publish
            
workflows:
    version: 2
    build-test-cov-deploy:
        jobs:
            - build
            - test:
                requires:
                    - build
            - coverage:
                requires:
                    - build
            - docs:
                requires:
                    - build
            - deploy:
                filters:
                    branches:
                        only: master
                requires:
                    - test
                    - docs
                    - coverage